title: Texas Wastelands
email: admin@texaswastelands.com
description: >-
  Game development, technical design, AI-assisted software projects, and prototypes by Nathan Howard.
baseurl: ""
url: "https://texaswastelands.github.io"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

remote_theme: pages-themes/hacker@v0.2.0
theme: minima
