name: Notify Discord on Push

on:
  push:
    branches:
      - main  # or the branches you want to monitor
      - dev

jobs:
  discordNotify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            New push to **${{ github.repository }}** by **${{ github.actor }}**.
            Commit message: _${{ github.event.head_commit.message }}_
